### ISSUE TITLE
Survival Mode Task List

### ISSUE THREAD

**Issue by freakpants** [freakpants/musicguess#174]
- [ ] Update Online Database from local database
- [ ] Find a way to regularly get new tracks into local database
- [ ] Duplicate detection, so that player doesn't get the same song twice or almost the same one

**Comment by freakpants** [comment]
Examples:
Player gets Song "Sexual" => Sexual (Li Da Di) should not be played.
But Player gets Song "Sexual (Li Da Di)" -> Sexual should also not be played
